// src/components/vue2/Counter.vue
<template>
  <div>
    <h2>Vue 2 组件：Counter</h2>
    <p>Count: <strong>{{ count }}</strong></p>
    <button @click="count--">-1</button>
    <button @click="count++">+1</button>
  </div>
  
</template>

<script>
export default {
  name: 'VueCounter',
  data() {
    return { count: 0 };
  }
};
</script>

<style scoped>
</style>

// src/components/react/Counter.jsx
import React from 'react';

export default function Counter() {
  const [count, setCount] = React.useState(0);
  return (
    React.createElement('div', null,
      React.createElement('h2', null, 'React 组件：Counter'),
      React.createElement('p', null, 'Count: ', React.createElement('strong', null, count)),
      React.createElement('button', { onClick: () => setCount(count - 1) }, '-1'),
      React.createElement('button', { onClick: () => setCount(count + 1) }, '+1')
    )
  );
}
